### ISSUE TITLE
Option for adding modules in init-drupal

### ISSUE THREAD

**Issue by subhojit777** [axelerant/axl-template#13]
### Motivation:

It would be great if one would be able to add any composer packages, modules while creating a Drupal codebase.

**Comment by subhojit777** [comment]
FYI @hussainweb

**Comment by hussainweb** [comment]
@subhojit777 +1 to this. I want this from quite some time. I am wondering how best to add this option. Two straight-forward choices are as a list of names as arguments or a new option.

As argument:
```
init-drupal axl/test admin_toolbar search_api search_api_solr:"^4.0"
```

OR as an option:
```
init-drupal axl/test -m admin_toolbar -m search_api -m search_api_solr:"^4.0"
```

OR is there a better alternative?

**Comment by subhojit777** [comment]
IMO the second one looks more concise.

**Comment by hussainweb** [comment]
@subhojit777, the second option is longer and you have to type more. How is more concise?

**Comment by subhojit777** [comment]
well.. I was thinking about the specific flag `-m` for adding the packages, hence, a self-understandable command for adding the packages.

Although the first option looks good too, but I usually check the flags while using a command. I usually don't worry how long it is.. (I use repititive search) I think this is always going to be user's preference :)

I think we can finalize anyone and later make modifications :)
