### ISSUE TITLE
phpcs and phpcpd errors while doing initial commit.

### ISSUE THREAD

**Issue by devtaher** [axelerant/axl-template#16]
**Problem statement :** 

I installed a Drupal 9 website using the template and while making an initial commit I faced the following issues :

![axl_template_errors](https://user-images.githubusercontent.com/3863292/87752703-9d308c00-c81e-11ea-9b01-0d365f80b659.jpg)

**Solution :** 

1. Add relevant comments  in the files failing the phpcs on commit.

   I will be creating a PR for this. 

2. At the moment I am not able figure out a way to fix the phpcpd error as it is looking for  `./web/modules/custom` which is not present as I don't have any custom modules on my site yet.

**Comment by hussainweb** [comment]
@devtaher, I assume that the `phpcpd` error was not fixed by #17. I would prefer fixing that by creating the directory and a `.gitkeep` file under there. Do you want to create a PR for that as well?

**Comment by devtaher** [comment]
@hussainweb Thanks for suggesting the solution, I will create a PR for it.

**Comment by hussainweb** [comment]
Both PRs merged
