### ISSUE TITLE
Should composer install be optional by default?

### ISSUE THREAD

**Issue by skippednote** [axelerant/axl-template#2]
Considering the following factors:
1. Not everyone using this project wouldn't have composer binary or the right version of composer 
2. or might not want to run composer install immediately after scaffolding

I propose making it optional by default which would mean changing `--no-install` to `--install`.

**Comment by hussainweb** [comment]
I thought about this and I too avoid negative arguments. In this case, though, I thought it best to just emulate `composer create-project` convention of having `no-install`.

As for your first point: For the target audience, I think it much more likely that they would use `composer` enough to have it installed globally.

**Comment by skippednote** [comment]
>As for your first point: For the target audience, I think it much more likely that they would use composer enough to have it installed globally.
I guess we are good here for now. We should, however, we should list composer as a dependency in that case.
