### ISSUE TITLE
Change the default for the directory option

### ISSUE THREAD

**Issue by hussainweb** [axelerant/axl-template#20]
The directory option is confusing and prone to errors. It might be better to just ensure that the current directory is empty and if it isn't, throw an error asking the user to create a new directory and run the command there.

Alternatively, we can keep the `--directory` option and make it optional. If it is an empty string (or `.`), we check if the current directory is empty.

Neither of the above breaks the current workflow significantly. The current workflow also gives an error if the directory exists.

**Comment by mehulshah1506** [comment]
How about creating a directory with a specific name, if the `--directory ` not provided. Just like what Git does.

**Comment by hussainweb** [comment]
@mehulshah1506, can you clarify what git does? I'm not sure which command you're referring to. For example, `git init` initializes a repo in the current directory.

Also, currently, if `--directory` is not provided, it defaults to `drupal`. That's the confusing part. If someone doesn't provide this option, it's not intuitive that they have to look for a directory called `drupal`.

**Comment by mehulshah1506** [comment]
Apologies for not providing enough details. 

I was referring to `git clone <repo> <directory>`  where `<directory>` is optional.

Once properly initialized, display a message where it has been initialized.

**Comment by hussainweb** [comment]
@mehulshah1506, I see what you mean and it makes sense. In our case, right now, we have `init-drupal vendor/site`. We could default the directory to `site`.

**Comment by hussainweb** [comment]
With that in mind, I think #20 is still a step in the right direction. I'll merge that and work on the change as per my last comment.

**Comment by hussainweb** [comment]
Fixed in #22.
